### ISSUE TITLE
Channel types?

### ISSUE THREAD

**Issue by AdamJSoftware** [jq-rs/mles-rs#158]
Does MLES support different channel/exchange types like rabbitmq? Fanout, Direct, Topic, and Headers. Or is every channel just a fanout channel? If so, is there a way to implement the others in the client?

**Comment by jq-rs** [comment]
Thanks for the question! Fanout it is, but you can probably accomplish most of the other types with several channels. E.g. for one-to-one messages, just create a channel with two members and so forth.

As such the messages are transparent for the server and can be fully end-to-end encrypted as well, so I do not think such channel types fit for Mles nor they can or should be implemented.

Let me know if you need more info for a specific case etc.
